### PR TITLE
Updated Script to count only Unique Rows, Updated passwords.csv

### PR DESCRIPTION
**Pull request by siddhantdixit**
Removed Duplicate Rows in passwords.csv

Replaced empty Username and Password columns with <blank> in passwords.csv

Updated the shell script to count only Unique Rows and update the ReadMe file according to this.

### CODE REVIEW

**Comment by piechowiakmichal** [comment]
Hi! Unfortunately Github Actions ([https://www.githubstatus.com/](https://www.githubstatus.com/)) still doesn't work, so at the moment I can't test it.

Sorry for the delay.

**Comment by piechowiakmichal** [comment]
Hi, I thought you would replace blank username and password entries with ``<blank>``, but okay.

The script works almost fine, it doesn't recognize uppercase and lowercase, can you fix it?

**Comment by siddhantdixit** [comment]
@piechowiakmichal Fixed the issue uppercase case and lower case issue. Fields with the same value and different cases will be counted differently.
Now empty Username and Password fields in passwords.csv will change to <blank> from script.

**Review by piechowiakmichal — APPROVED** [review]

**Review by piechowiakmichal — APPROVED** [review]

**Review by piechowiakmichal — APPROVED** [review]

**Comment by siddhantdixit** [comment]
Sure

**Pull request merged**
